### PR TITLE
Don't add unsubscribe hash link to the message automatically

### PR DESCRIPTION
**Pull request by stalkernoid**
Instead this commit adds a checkbox that you need to check if you
want your message to have the unsubscribe hash link.

### CODE REVIEW

**Comment by kylemhall** [comment]
@stalkernoid if you can resubmit this request with the option to remove the unsubscribe link as an option read from koha-conf.xml we can merge your request.

**Comment by taskula** [comment]
I would also like to see this merged.

One of our installations has completely disabled Koha OPAC making unsubscribe endpoint based on OPACBaseURL inaccessible. Also it seems that the unsubscribe notice is not currently translatable. While these issues can be solved individually in separate pull requests, this PR would provide a simple solution that works for us.

I'm not sure adding plugin options to koha-conf.xml is good practice as I think librarians/superuser should be able to configure plugins as much as possible in staff client.

**Comment by kylemhall** [comment]
@taskula the control for this needs to be in the config so that system wide policies cannot be overridden by an individual.

**Comment by stalkernoid** [comment]
Rebased and made that link optional depending on the checkbox parameter:
https://github.com/bywatersolutions/koha-plugin-patron-emailer/pull/45

**Pull request closed without merging**
